
platform :ios, '10.0'
use_frameworks!
install! 'cocoapods', :deterministic_uuids => false

source 'git@github.com:applicaster/CocoaPods.git'
source 'git@github.com:CocoaPods/Specs.git'
source 'git@github.com:applicaster/CocoaPods-Private.git'
source 'git@github.com:applicaster/PluginsBuilderCocoaPods.git'
source 'git@github.com:applicaster/applicaster-iap-framework'
source 'git@github.com:applicaster/applicaster-cam-framework'

target 'CleengLoginPlugin' do
  pod 'CleengLogin', :path => '../CleengLogin.podspec'
  pod 'CAM', :path => '../Submodules/CAM/CAM.podspec'
end
